# Generated by Django 3.2.8 on 2021-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'Формируется'), ('STP', 'Отправлен на обработку'), ('PRD', 'Обработан'), ('PD', 'Оплачен'), ('DN', 'Готов'), ('CN', 'Отменён')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
