# Generated by Django 3.2.8 on 2021-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20211123_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('И', 'Иное')], default='И', max_length=1, verbose_name='Пол'),
        ),
    ]
